### ISSUE TITLE
CSS: Cyrillic and numbers  in variable names

### ISSUE THREAD

**Issue by kondyan2022** [O-TYSHCHENKO/food-sta-tp#9]
```:root {
    --color-button-green: #bbf330;
    --color-dark-green: #7eb101;
    --color-yellow-main: #ffe550;
    --color-black: #2c2c2c;
    --color-white: #fefefe;
    --color-shadow-fruit: radial-gradient(#2f583f 0%, #696969 100%);
    --color-2: #a7ce47;
    --color-текст: #3d3d3d;
    --color-текст-2: #969696;
    --color-текст-3: #4a4a4a;
    --color-grad-1: linear-gradient(to bottom, #fe88b3 0%, #ff4d8d 100%);
    --color-grad-2: linear-gradient(to bottom, #fdfdfd 0%, #fff5f9 23.87%, #fe88b3 100%);
}
`

**Comment by O-TYSHCHENKO** [comment]
Привет! Поддерживаю замечание: кириллица и прочие спец.символы не используются в именах классов, переменных и т.п. 
Поскольку изначально за основу я взял код для файла .css (путем прямой заливки на главную ветку) из первого pull request (by Андрей), сейчас также внес прямые корректировки -
удалены такие строки в главной ветке:

  --color-2: #a7ce47;
  --color-текст: #3d3d3d;
  --color-текст-2: #969696;
  --color-текст-3: #4a4a4a;

Прошу автора просмотреть оставшийся код в  css на предмет корректности.
НО на будущее, такие моменты конечно-же будут решаться путем pull request!

**Comment by kondyan2022** [comment]
fixing
